name: vowce_mail_server
description: A pure Dart server for sending magic links via Resend
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.3.0
  shared_preferences: ^2.3.3
